name: castle_flutter_web
description: Web platform implementation of castle_flutter
version: 1.0.0

publish_to: none

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CastleFlutterWeb
        fileName: castle_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  castle_flutter_platform_interface:
    path: ../castle_flutter_platform_interface/

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"