name: castle_flutter_platform_interface
description: A common platform interface for the castle_flutter plugin.
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"
