name: castle_flutter_example
description: Demonstrates how to use the castle_flutter plugin.

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  castle_flutter:
    path: ../
  cupertino_icons: ^1.0.0

dependency_overrides:
  castle_flutter:
    path: ../
  castle_flutter_platform_interface:
    path: ../../castle_flutter_platform_interface
  castle_flutter_web:
    path: ../../castle_flutter_web

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
